# Generated by Django 3.0.9 on 2020-09-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default.jpeg', height_field=500, upload_to='', width_field=600),
        ),
    ]
